{"name": "Проверьте, что повторная регистрация с уже существующим логином выдаёт сообщение об ошибке", "status": "passed", "attachments": [{"name": "log", "source": "fc56d204-0eda-4fdd-b33c-f9222f10a625-attachment.txt", "type": "text/plain"}], "start": 1732986843346, "stop": 1732986845256, "uuid": "8514a4f9-1b68-41bf-a39a-70d2c41fdc72", "historyId": "c8d0206f535b3696d741ddaf3a0d6e3e", "testCaseId": "c8d0206f535b3696d741ddaf3a0d6e3e", "fullName": "tests#test_2", "labels": [{"name": "feature", "value": "Тестирование регистрации"}, {"name": "suite", "value": "tests"}, {"name": "host", "value": "DESKTOP-6QGNUCQ"}, {"name": "thread", "value": "20728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}